name: ShieldNet Linux Debian Package Builder for ARM64

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - debian-pkg-manager-arm64-v*

jobs:
  build-deb:
    runs-on: ubuntu-22.04-arm64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: White-label
        run: | 
          ./white-lable.sh

      - name: Setup Docker
        id: setup-docker
        uses: docker/setup-docker-action@v4

      - name: build-pkg
        id: build-shieldnet
        run: |
          cd packages
          sudo ./generate_package.sh -t manager -a arm64 -s ~/shieldnet-linux-pkg-manager-arm64 --system deb

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: ShieldNet Linux Manager Packages
          path: ~/shieldnet-linux*
