name: ShieldNet Linux Debian Package Builder

on:
  push:
    tags:
      - debian-pkg-v*

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        id: setup-docker
        uses: docker/setup-docker-action@v4

      - name: build-pkg
        id: build-shieldnet
        run: |
          echo "White-labeling the package..."
          ./white-lable.sh
          echo "Building the package..."
          cd packages
          sudo ./generate_package.sh -t agent -a amd64 -s ~/shieldnet-linux-pkg-amd64 --system deb

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: ShieldNet Linux Packages
          path: ~/shieldnet-linux*